spring:
  jpa:
    hibernate:
      ddl-auto: update

application:

  security:
    jwt:
      secret-key: NXiq/nDgIORAC2Gij/th6ukfF1uFax7H+9LfFl+UhN5fBuMn1TesTK/7eD4e5Z4X8JYTm5tQm6mXyMqr
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days